# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.destroy_all

books = [
  {:title => "To Kill A Mocking Bird", :author => "Harper Lee"},
  {:title=>"1984", :author=>"George Orwell"},
  {:title=>"The Lord of the Rings", :author=>"J.R.R. Tolkien"},
  {:title=>"The Catcher in the Rye", :author=>"J.D. Salinger"},
  {:title=>"The Great Gatsby", :author=>"F. Scott Fitzgerald"},
  {:title=>"The Lion, the Witch, and the Wardrobe", :author=>"C.S. Lewis"},
  {:title=>"Lord of the Flies", :author=>"William Golding"},
  {:title=>"Animal Farm", :author=>"George Orwell"},
  {:title=>"Catch-22 (Catch-22, #1)", :author=>"Joseph Heller"},
  {:title=>"The Grapes of Wrath", :author=>"John Steinbeck"},
  {:title=>"Gone with the Wind", :author=>"Margaret Mitchell"},
  {:title=>"Slaughterhouse-Five", :author=>"Kurt Vonnegut Jr."},
  {:title=>"Lolita", :author=>"Vladimir Nabokov"},
  {:title=>"One Flew Over the Cuckoo's Nest", :author=>"Ken Kesey"},
  {:title=>"A Clockwork Orange", :author=>"Anthony Burgess"},
  {:title=>"Are You There God? It's Me, Margaret", :author=>"Judy Blume"},
  {:title=>"Watchmen", :author=>"Alan Moore"},
  {:title=>"Never Let Me Go", :author=>"Kazuo Ishiguro"},
  {:title=>"Atonement", :author=>"Ian McEwan"},
  {:title=>"Things Fall Apart (The African Trilogy, #1)", :author=>"Chinua Achebe"},
  {:title=>"Beloved", :author=>"Toni Morrison"},
  {:title=>"Invisible Man", :author=>"Ralph Ellison"},
  {:title=>"Mrs. Dalloway", :author=>"Virginia Woolf"},
  {:title=>"The Sun Also Rises", :author=>"Ernest Hemingway"},
  {:title=>"On the Road", :author=>"Jack Kerouac"},
  {:title=>"Possession", :author=>"A.S. Byatt"},
  {:title=>"The Big Sleep (Philip Marlowe, #1)", :author=>"Raymond Chandler"},
  {:title=>"A Passage to India", :author=>"E.M. Forster"},
  {:title=>"I, Claudius (Claudius, #1)", :author=>"Robert Graves"},
  {:title=>"Their Eyes Were Watching God", :author=>"Zora Neale Hurston"},
  {:title=>"The Sound and the Fury", :author=>"William Faulkner"},
  {:title=>"All the King's Men", :author=>"Robert Penn Warren"},
  {:title=>"The Blind Assassin", :author=>"Margaret Atwood"},
  {:title=>"Native Son", :author=>"Richard Wright"},
  {:title=>"To the Lighthouse", :author=>"Virginia Woolf"},
  {:title=>"Ragtime", :author=>"E.L. Doctorow"},
  {:title=>"The French Lieutenant's Woman", :author=>"John Fowles"},
  {:title=>"The Heart Is a Lonely Hunter", :author=>"Carson McCullers"},
  {:title=>"Light in August", :author=>"William Faulkner"},
  {:title=>"Naked Lunch", :author=>"William S. Burroughs"},
  {:title=>"The Spy Who Came In from the Cold", :author=>"John le Carré"},
  {:title=>"Blood Meridian, or the Evening Redness in the West", :author=>"Cormac McCarthy"},
  {:title=>"White Noise", :author=>"Don DeLillo"},
  {:title=>"Infinite Jest", :author=>"David Foster Wallace"},
  {:title=>"Snow Crash", :author=>"Neal Stephenson"},
  {:title=>"Revolutionary Road", :author=>"Richard Yates"},
  {:title=>"Brideshead Revisited: The Sacred and Profane Memories of Captain Charles Ryder", :author=>"Evelyn Waugh"},
  {:title=>"Midnight's Children", :author=>"Salman Rushdie"},
  {:title=>"The Prime of Miss Jean Brodie", :author=>"Muriel Spark"},
  {:title=>"Death Comes for the Archbishop", :author=>"Willa Cather"},
  {:title=>"The Bridge of San Luis Rey", :author=>"Thornton Wilder"},
  {:title=>"Neuromancer (Sprawl, #1)", :author=>"William Gibson"},
  {:title=>"American Pastoral (The American Trilogy, #1)", :author=>"Philip Roth"},
  {:title=>"The Corrections", :author=>"Jonathan Franzen"},
  {:title=>"The Power and the Glory", :author=>"Graham Greene"},
  {:title=>"The Crying of Lot 49", :author=>"Thomas Pynchon"},
  {:title=>"Portnoy's Complaint", :author=>"Philip Roth"},
  {:title=>"Wide Sargasso Sea", :author=>"Jean Rhys"},
  {:title=>"Gravity's Rainbow", :author=>"Thomas Pynchon"},
  {:title=>"Red Harvest", :author=>"Dashiell Hammett"},
  {:title=>"Rabbit, Run (Rabbit Angstrom #1)", :author=>"John Updike"},
  {:title=>"White Teeth", :author=>"Zadie Smith"},
  {:title=>"Under the Volcano", :author=>"Malcolm Lowry"},
  {:title=>"The Painted Bird", :author=>"Jerzy Kosiński"},
  {:title=>"Go Tell It on the Mountain", :author=>"James     Baldwin"},
  {:title=>"A House for Mr Biswas", :author=>"V.S. Naipaul"},
  {:title=>"Play It as It Lays", :author=>"Joan Didion"},
  {:title=>"Lucky Jim", :author=>"Kingsley Amis"},
  {:title=>"Ubik", :author=>"Philip K. Dick"},
  {:title=>"The Golden Notebook", :author=>"Doris Lessing"},
  {:title=>"The Heart of the Matter", :author=>"Graham Greene"},
  {:title=>"Pale Fire", :author=>"Vladimir Nabokov"},
  {:title=>"The Moviegoer", :author=>"Walker Percy"},
  {:title=>"The Confessions of Nat Turner", :author=>"William Styron"},
  {:title=>"Tropic of Cancer", :author=>"Henry Miller"},
  {:title=>"Appointment in Samarra", :author=>"John O'Hara"},
  {:title=>"Money", :author=>"Martin Amis"},
  {:title=>"Deliverance", :author=>"James Dickey"},
  {:title=>"The Day of the Locust", :author=>"Nathanael West"},
  {:title=>"Housekeeping", :author=>"Marilynne Robinson"},
  {:title=>"The Man Who Loved Children", :author=>"Christina Stead"},
  {:title=>"The Sot-Weed Factor", :author=>"John Barth"},
  {:title=>"The Adventures of Augie March", :author=>"Saul Bellow"},
  {:title=>"Herzog", :author=>"Saul Bellow"},
  {:title=>"At Swim-Two-Birds", :author=>"Flann O'Brien"},
  {:title=>"Call It Sleep", :author=>"Henry Roth"},
  {:title=>"The Sheltering Sky", :author=>"Paul Bowles"},
  {:title=>"A Handful of Dust", :author=>"Evelyn Waugh"},
  {:title=>"The Sportswriter", :author=>"Richard Ford"},
  {:title=>"The Berlin Stories: The Last of Mr Norris/Goodbye to Berlin", :author=>"Christopher Isherwood"},
  {:title=>"A Death in the Family", :author=>"James Agee"},
  {:title=>"The Recognitions", :author=>"William Gaddis"},
  {:title=>"Dog Soldiers", :author=>"Robert  Stone"},
  {:title=>"The Assistant", :author=>"Bernard Malamud"},
  {:title=>"Loving", :author=>"Henry Green"},
  {:title=>"Under the Net", :author=>"Iris Murdoch"},
  {:title=>"A Dance to the Music of Time: 1st Movement (A Dance to the Music of Time, #1-3)", :author=>"Anthony Powell"},
  {:title=>"An American Tragedy", :author=>"Theodore Dreiser"},
  {:title=>"Falconer", :author=>"John Cheever"},
  {:title=>"The Death of the Heart", :author=>"Elizabeth Bowen"}]

  books.each do |book|
    Book.create!(title: book[:title], author: book[:author])
  end

  puts "Created #{books.count} books"
